export const CLIENTS = [
  'Absolute Communications, Inc.',
  'AE Works',
  'Airspan',
  'Americom',
  'ANDREW',
  'AP Wireless',
  'Arium Networks',
  'AT&T',
  'Ballast Networks',
  'Boingo',
  'Boldyn',
  'Celona',
  'Circet',
  'Connectivity Wireless',
  'Crown Castle',
  'EC Sites',
  'Ericsson',
  'Fortress Solutions',
  'Glow Networks',
  'Graystone Communications',
  'Halo',
  'Matsing',
  'Metro Electric',
  'Mobile Communications America',
  'MTSI Solutions Inc',
  'Nokia',
  'PowerCom',
  'Repeated Signal Solutions',
  'RFS Technologies',
  'RK Squared',
  'Stanford',
  'Tekgence',
  'Telcom Gateway',
  'TEPS',
  'TMobile',
  'Totem Cellular',
  'Verizon',
  'Vision Technologies',
] as const

export type ClientName = (typeof CLIENTS)[number]

const CLIENT_INITIALS: Record<string, string> = {
  'Absolute Communications, Inc.': 'ACI',
  'AE Works': 'AEW',
  'Airspan': 'AIR',
  'Americom': 'AMR',
  'ANDREW': 'AND',
  'AP Wireless': 'APW',
  'Arium Networks': 'ARN',
  'AT&T': 'ATT',
  'Ballast Networks': 'BLN',
  'Boingo': 'BOI',
  'Boldyn': 'BLD',
  'Celona': 'CEL',
  'Circet': 'CIR',
  'Connectivity Wireless': 'CNW',
  'Crown Castle': 'CRC',
  'EC Sites': 'ECS',
  'Ericsson': 'ERI',
  'Fortress Solutions': 'FSO',
  'Glow Networks': 'GLN',
  'Graystone Communications': 'GRC',
  'Halo': 'HAL',
  'Matsing': 'MAT',
  'Metro Electric': 'MTE',
  'Mobile Communications America': 'MCA',
  'MTSI Solutions Inc': 'MSI',
  'Nokia': 'NOK',
  'PowerCom': 'PCM',
  'Repeated Signal Solutions': 'RSS',
  'RFS Technologies': 'RFS',
  'RK Squared': 'RKS',
  'Stanford': 'STF',
  'Tekgence': 'TEK',
  'Telcom Gateway': 'TGW',
  'TEPS': 'TEP',
  'TMobile': 'TMO',
  'Totem Cellular': 'TCL',
  'Verizon': 'VRZ',
  'Vision Technologies': 'VTI',
}

export function generateProjectCode(client: string): string {
  const initials = CLIENT_INITIALS[client] ?? 'PRJ'
  const year = new Date().getFullYear().toString().slice(-2)
  const rand = Math.floor(Math.random() * 10000).toString().padStart(4, '0')
  return `${initials}${year}${rand}`
}
