export const FIELD_ENGINEERS: { name: string; email: string }[] = [
  { name: 'Abdul Fateh', email: 'afateh@americloudtelecom.com' },
  { name: 'Nasrulla Ataulla', email: 'nkhan@americloudtelecom.com' },
  { name: 'Nadeem Rasool', email: 'nrasool@americloudtelecom.com' },
  { name: 'Arnel Avecilla', email: 'aavecilla@americloudtelecom.com' },
  { name: 'Jihad Mounir', email: 'jmounir@americloudtelecom.com' },
  { name: 'Naaman Bakshi', email: 'nbakhshi@americloudtelecom.com' },
  { name: 'Faizan Khan', email: 'fakhan@americloudtelecom.com' },
  { name: 'Humzah Shoaib', email: 'hshoaib@americloudtelecom.com' },
  { name: 'Alexis Pena', email: 'apena@americloudtelecom.com' },
  { name: 'Furquan Ahmed', email: 'mfahmed@americloudtelecom.com' },
  { name: 'Rayyan Ansari', email: 'ransari@americloudtelecom.com' },
  { name: 'Qais Khader', email: 'qkhadher@americloudtelecom.com' },
  { name: 'Amaechi Nwankwo', email: 'anwankwo@americloudtelecom.com' },
  { name: 'Joselito Araneta', email: 'jaraneta@americloudtelecom.com' },
  { name: 'Isaiah Nicasio', email: 'inicasio@americloudtelecom.com' },
  { name: 'Ferdinand Nicasio', email: 'fnicasio@americloudtelecom.com' },
  { name: 'Daniel Lapada', email: 'dlapada@americloudtelecom.com' },
  { name: 'Manish Bommakanti', email: 'mbommakanti@americloudtelecom.com' },
  { name: 'Abelino Bautista', email: 'abautista@americloudtelecom.com' },
  { name: 'James Faux', email: 'jfaux@americloudtelecom.com' },
  { name: 'Sai Manikanta Kolla', email: 'smkolla@americloudtelecom.com' },
  { name: 'Peter Tijing', email: 'ptijing@americloudtelecom.com' },
  { name: 'Sri Vishnu Yadala', email: 'svyadala@americloudtelecom.com' },
  { name: 'Gary S. Polloso', email: 'gpolloso@americloudtelecom.com' },
  { name: 'Ajay Kumar Andappally', email: 'ajkumar@americloudtelecom.com' },
  { name: 'Dinesh Pottunuri', email: 'dpottunuri@americloudtelecom.com' },
  { name: 'Arvin Mariano', email: 'amariano@americloudtelecom.com' },
  { name: 'Thirumalesh Naggari', email: 'tnaggari@americloudtelecom.com' },
  { name: 'Sai Girish Behara', email: 'N/A' },
]
